---
name: ambassador
namespace: loadtest
replicas: 3
ambassadorImage: dwflynn/ambassador:0.27.0-DRAFT.0

cloud: aws
aws:
  listenPort: 80
  sslCertificateArn:
  useProxyProtocol: true

profiles:
  dev:
    name: {{ branch.replace('/', '-') }}
  staging:
    name: next
  stable:
    name: stable

branches:
  master: stable
  dev/*:  dev
