---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ build.name }}-admin
  name: {{ build.name }}-admin
  namespace: {{ service.namespace }}
spec:
  type: NodePort
  ports:
  - name: {{ build.name }}-admin
    port: 8877
    targetPort: 8877
  selector:
    service: {{ build.name }}

{% if service.cloud | default("none") | lower == "aws" %}
{% include "service-aws-loadbalancer.include" %}
{% else %}
{% include "service-any-nodeport.include" %}
{% endif -%}
