---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace | default("default") }}
  labels:
    app: {{ build.name }}
spec:
  replicas: {{ service.replicas }}
  template:
    metadata:
      labels:
        app: {{ build.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: datawire.io/workload
                operator: In
                values:
                - any
      serviceAccountName: {{ build.name }}
      restartPolicy: Always
      containers:
        - name: ambassador
          image: {{ service.ambassadorImage }}
          resources:
            limits:
              cpu: 1
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 100Mi
          ports:
            - name: ingress
              containerPort: 80
          env:
            - name: SCOUT_DISABLE
              value: "1"
            - name: AMBASSADOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: 8877
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: 8877
            initialDelaySeconds: 3
            periodSeconds: 3
