---
apiVersion: v1
kind: Service
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
  labels:
    app: {{ build.name }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: {{ build.name }}
      prefix: /
      host: {{ build.name }}.datawire.io
      service: {{ build.name }}.{{ service.namespace }}

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: {{ build.name }}-websocket
      prefix: /ws
      rewrite: /ws
      use_websocket: true
      host: {{ build.name }}.datawire.io
      service: {{ build.name }}.{{ service.namespace }}
spec:
  selector:
    app: {{ build.name }}
  type: ClusterIP
  ports:
    - name: http-api
      port: 80
      protocol: TCP
      targetPort: http-api

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace }}
  labels:
    app: {{ build.name }}
spec:
  replicas: {{ service.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ build.name }}
    spec:
      containers:
        - name: targetpractice
          image: {{ build.images["Dockerfile"] }}
          ports:
            - name: http-api
              containerPort: 7000
