---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ build.name }}-master
  name: {{ build.name }}-master
spec:
  ports:
  - name: protocol
    port: 5557
    targetPort: protocol
  - name: protocol-plus-1
    port: 5558
    targetPort: protocol-plus-1
  - name: web-ui
    port: 8089
    targetPort: web-ui
  selector:
    app: {{ build.name }}-master
