---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}-slave
  labels:
    app: {{ build.name }}-slave
  namespace: {{ service.namespace }}
spec:
  replicas: {{ service.replicas }}
  selector:
    matchLabels:
      app: {{ build.name }}-slave
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ build.name }}-slave
    spec:
      containers:
        - name: locust-slave
          image: {{ build.images["Dockerfile"] }}
          imagePullPolicy: IfNotPresent
          env:
            - name: LOCUST_TARGET
              valueFrom:
                configMapKeyRef:
                  name: {{ build.name }}-config
                  key: LOCUST_TARGET
            - name: LOCUST_MODE
              value: SLAVE
            - name: LOCUST_MASTER_HOST
              value: {{ build.name }}-master
            - name: LOCUST_OPTS
              value: --print-stats
          ports:
            - name: protocol
              containerPort: 5557
            - name: protocol-plus-1
              containerPort: 5558
            - name: web-ui
              containerPort: 8089
